#!/usr/bin/env python3.10

from os import getcwd
path.append(getcwd() + "/src") # fetch src/ to get the main's module

from sys import argv as av, path

from Goodnight import main

if (__name__ == "__main__"): exit(main(len(av), av))
